### ISSUE TITLE
Invalid casing for Activity ID

### ISSUE THREAD

**Issue by dagavriliu** [RusticiSoftware/TinCan.NET#10]
From the TinCan API spec, I believe that the ActivityID specified as a query parameter should be case-sensitive. 
While using an Uri object to store the ActivityID, this is actually helpful in ensuring proper format, URIs in .Net are case insensitive and actually lose their casing when converted to string. I suggest using a different approach that can keep the original casing. I found Uri.OriginalString to be helpful.
This behavior is implemented in TinCan.StatementsQuery.ToParameterMap()
I hope you can also review this for the other parameters as well.

**Comment by brianjmiller** [comment]
Activity IDs are now being handled as a string (hopefully everywhere) which should alleviate this problem based on #20 being merged, and I'll be cutting a new major release with that change since it breaks backwards compatibility. Re-open if your case isn't fixed.
