### ISSUE TITLE
Is it possible to make a tincan zip package after integrating this library?

### ISSUE THREAD

**Issue by svermeulen** [RusticiSoftware/TinCan.NET#19]
I've successfully integrated this library into my Unity3D application.  However, I now have a client that is asking for me to provide a "tincan zip package".

My understanding is that tincan zip packages can be dropped into any LMS and will automatically send statements to that LMS.  This seems problematic for me because I am currently hard-coding the URL for the endpoint in my application, and passing it to the `RemoteLRS` constructor.

From what I've read on the `tincanapi.com`, the tincan zip package needs to include a tincan.xml file at the root of the package, then it looks like it retrieves the endpoint and user information by parsing the URL query parameters?  This is where I'm a bit unclear.

So my question is, now that I'm successfully using the TinCan.NET library in my application, how do I make my application into a tincan zip package?

Thanks

**Comment by garemoko** [comment]
@svermeulen I don't think I have a complete answer for you, but below is some information relating to your question which I think will be helpful. 

1. The TinCan.xml method is just one method of launch Tin Can. You can support Tin Can without using this launch method. It may be, for example, that you have the LMS just Hyperlink to your application installed on another server and that your application contains or collects all the information it needs to send the data to the LRS. 

2. If you use the tincan.xml method, you don't have to include the files in the package. The tincan.xml can link out to externally hosted files. 

3. As .NET is a server side language, I don't expect you'd be able to include .NET code in a client side package. That said, maybe Unity's packager does something clever. I'm not very familiar with Unity. You'd probably get a better answer to this part of the question from Unity forums or somewhere like that. 

4. If you like, you can send Tin Can data to multiple LRSs, e.g. one determined by a launch query-string and one embedded in the package. That way you get the data in your external LRS and in the LMS. 

5. The Tin Can prototypes have some examples of tincan.xml files: http://tincanapi.com/prototypes/download-prototypes

Please feel free to ask follow up questions. 

Andrew

**Comment by svermeulen** [comment]
Thanks Andrew, that is helpful.

Yeah, Unity actually does allow you to write C# code on the client.  Users have to install their browser plugin and then the C# code runs in a sandbox environment with web restrictions

Ok I think I'm getting an idea of what I need to do now.  I understand that you don't have to use tincan.xml but in my case I do because that's what the client wants  :)    So it sounds like I have to reproduce some of the functionality of the Tin Can Driver myself - which would include:

1. Creating a tincan.xml file
2. Parsing information from the query string such as LMS URL, user authentication information, etc.   It sounds like nobody has done this yet in C#, probably because like you said, most people aren't running C# in a web environment on the client.

Is that all that I would need to properly create a tincan zip package?

**Comment by brianjmiller** [comment]
This type of file is based off a set of LMS guidelines that were released with the 0.9 spec. They can be found here: https://github.com/RusticiSoftware/launch/blob/master/lms_lrs.md

You are correct in the steps necessary. AFAIK the only implementation of this on the client side is TinCanJS' `TinCan` interface which you could look at for guidance (it is what the aforementioned prototypes use). See it here: https://github.com/RusticiSoftware/TinCanJS/blob/master/src/TinCan.js#L190

**Comment by svermeulen** [comment]
OK thanks, I'll give that a shot.

**Comment by svermeulen** [comment]
Ok I thought this change was going well but now I'm hitting an issue with authorization when using the scorm cloud website.  I find that I can send tin can statements fine when hard-coding the authorization details but when I get the authorization details from the URL query parameters (the "auth" value), the scorm cloud website returns error 500 (internal server error).

In the TinCan.NET package, I noticed that it generates the auth value from a username and password like this:

    public static string CreateAuthToken(String username, String password)
    {
        return Convert.ToBase64String(Encoding.UTF8.GetBytes(username + ":" + password));
    }

It then prefixes the value with "Basic " to produce an authorization value that looks like (I added the x's)

    Basic c3ZXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXwbDNS

The "auth" parameter that SCORM cloud gives me also follows this format and looks like this:

    Basic OjE5NDUXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX4MA==

I also confirmed that if I only use the hard-coded auth value (generated using the CreateAuthToken method) it connects fine. But if I use the value given by the launch url query string, scorm cloud returns error 500.

I'm not sure what else to do at this point, so I'm kind of stuck.  One thing I'm wondering about is, why is the auth value given by the url different?  I would have assumed it would be generated the same way using the same username and password

Any ideas?

**Comment by brianjmiller** [comment]
SCORM Cloud creates short lived, expirable tokens for auth credentials for launch scenarios. The LRSResponse object returned by the LRS requests contains an HTTPResponse object that you should be able to inspect to get the actual response text body which will give us more information about why Cloud returned a 500.

**Comment by svermeulen** [comment]
Unfortunately, I am not getting anything beyond just "error 500".  The response body is empty.

**Comment by svermeulen** [comment]
The same error seems to occur if I just send completely invalid auth data back to scorm cloud.  So it seems like scorm cloud does not think the same auth data that it gives me is valid somehow.

I also wanted to mention that I can reproduce this error pretty easily without introducing any additional changes to this library, by just changing auth data to use a hard-coded value that matches the value that scorm cloud gives me for the "auth" parameter in the url.

**Comment by svermeulen** [comment]
Ok I think I may have figured this out.  If I pass this data as part of the PUT request to save a tin can statement it seems to accept it:

- content_endpoint
- externalConfiguration
- externalRegistration
- content_token

I can parse these values from the URL just like the auth and endpoint properties
