### ISSUE TITLE
LRS Save Statement ERROR- BUG

### ISSUE THREAD

**Issue by mwoodr1** [RusticiSoftware/TinCan.NET#24]
After putting all the necessary info into RemoteLRS (url, username, password), I receive an error trying to save the statement to the LRS. After I build the statement, I do a lrs.SaveStatement(statement)  but receive the following error
Error getting response stream (Write: The authentication or decryption has failed.): SendFailure. It happens in the MakeSyncRequest() once it hits the GetRequestStream() call.  Both myself and ADL get the same error even though ADL can see pinging of the IP address each time a statement attempts to be sent. Anyone know why this is an issue.

**Comment by brianjmiller** [comment]
Do you have a full stack trace? Some googling might suggest on of SSL certificate issue, security zone problem, or missing proxy settings. Having a more precise exception message would probably help troubleshoot. Others have also reported problems of not having certificate authorities installed particularly when doing Mono or Unity development.

**Comment by mwoodr1** [comment]
We updated the LRS url and it seems to have fixed that problem. And we are working in Unity 4.6.3 that seems that to have the neccessary support of certificates. We added some code that provided a workaround. However, we are not getting a request timeout in the MakeSyncRequest method. The full stacktrace is   
at System.Net.HttpWebRequest.GetRequestStream () [0x00000] in <filename unknown>:0 
 at TinCan.RemoteLRS.MakeSyncRequest (TinCan.MyHTTPRequest req) [0x00223] in C:\Projects\UnityProjects\E28_Maintenance_Trainer_xAPI\E28_NeL\Assets\plugins\Tincan\RemoteLRS.cs:165 
  at TinCan.RemoteLRS.SaveStatement (TinCan.Statement statement) [0x000cc] in C:\Projects\UnityProjects\E28_Maintenance_Trainer_xAPI\E28_NeL\Assets\plugins\Tincan\RemoteLRS.cs:431

**Comment by mwoodr1** [comment]
We checked our statements against the adl statement validator on the site. Here's an example:

{"actor":{"objectType":"Agent","name":"adlnavytest","mbox":"mailto:adlnavytest@adl.net"},"verb":{"id":"http://adlnet.gov/exapi/verbs/launched","display":{"en-US":"launched"}},"object":{"objectType":"Activity","id":"http://adlnet.github.io/xapi-lab","definition":{"description":{"en-US":"E-28 Training Course"}}},"timestamp":"2016-08-02T16:27:48.5936929-04:00","version":"1.0.1"}

**Comment by ganeshubhare** [comment]
Hello,
I am also getting similar error when using the HTTPS url when saving the statement. Heres the details of the error

WebException: Error writing request: The authentication or decryption has failed.
System.Net.WebConnectionStream.WriteHeaders ()
System.Net.WebConnectionStream.SetHeaders (System.Byte[] buffer)
(wrapper remoting-invoke-with-check) System.Net.WebConnectionStream:SetHeaders (byte[])
System.Net.HttpWebRequest.SendRequestHeaders (Boolean propagate_error)
Rethrow as WebException: Error: SendFailure (Error writing request: The authentication or decryption has failed.)
System.Net.HttpWebRequest.EndGetRequestStream (IAsyncResult asyncResult)
System.Net.HttpWebRequest.GetRequestStream ()
TinCan.RemoteLRS.MakeSyncRequest (TinCan.MyHTTPRequest req)
TinCan.RemoteLRS.SaveStatement (TinCan.Statement statement)
CameraController.Start () (at Assets/Scripts/CameraController.cs:39)

How can I fix this?

Please advise.

Thanks

**Comment by brianjmiller** [comment]
@ganeshubhare you're getting the certificate problem, I suggest having a look at http://stackoverflow.com/questions/4926676/mono-webrequest-fails-with-https?answertab=votes#tab-top

**Comment by brianjmiller** [comment]
@mwoodr1 did you ever get your issue resolved? Also what version of the library are you running cause the error message lines don't match up to the most recent version (which was out at the time) so I want to be sure to look at the right thing.
