### ISSUE TITLE
Statement Query?

### ISSUE THREAD

**Issue by mwoodr1** [RusticiSoftware/TinCan.NET#25]
I am attempting to use the StatementQuery class to create a query of a specific actor name. However, each time I query the LRS it returns all the statements regardless of actor name. My code is identical to the sample code for Statement query.

**Comment by garemoko** [comment]
@mwoodr1 are you populating the StatementsQuery agents property (`query.agents` in the example)?

See https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#723-getstatements for a list of query parameters.

**Comment by mwoodr1** [comment]
Yes. I've tried query.agent = new Agent();  query.agent = controller.name;  Controller name is the global name captured by our game that is passed into the actor.name when statements are built and sent.
I've also tried query.agent.name = controller.name; This one yields a object instance not created as it should.

**Comment by garemoko** [comment]
@mwoodr1 You are close, but the agent object needs to be an xAPI Agent. It's got the same data structure as the one in statements. 

You can't filter statements by the agent name though, only by their identifier. Which identifier are you using? Email, account or something else?

**Comment by garemoko** [comment]
Here's some code from the top example that uses email:

```
var actor = new Agent();
actor.mbox = "mailto:info@tincanapi.com";
```
