### ISSUE TITLE
Statement always fails with HTTPStatusCode 'OK'

### ISSUE THREAD

**Issue by bstevens762** [RusticiSoftware/TinCan.NET#36]
Hi, I'm a pretty experienced Unity dev with little to no web security experience and I've been struggling a lot to get xAPI working here over the last few months. Currently, I am using WebScarab to debug my HTTp traffic, and I see that each of my xAPI posts to the endpoint with code 200: Ok. However, within the code in Unity it is clear that OK is not okay, as HTTPStatusCode.OK causes lrsResponse.success to always return false. Thus, no UUID is generated and my statement doesn't post to the LRS. I do not understand why OK is not sufficient for xAPI in Unity, as the W3 documentation on HTTP status codes says that OK indicates "The request has succeeded. The information returned with the response is dependent on the method used in the request." Does something need to happen on my end? Or on the end of the LRS? I'd be happy to provide further details for anyone who may be able to help.

**Comment by garemoko** [comment]
Which LRS are you using? If it's a [conformant LRS](https://adopters.adlnet.gov/products/all/0) then a status code of 200 should indicate that the statement was stored successfully. 

The only scenarios I can think of where you'd get a 200 response and the statement not be stored are:

- You're not posting the statement to the LRS endpoint, just some random page that happens to return a 200 response to any request. 
- You're using the same statement id as an existing statement in the LRS (so the LRS assumes you are sending a duplicate of what it already has).

**Comment by garemoko** [comment]
It could also be that you are not actually getting a 200 request. To check that, have you tried using an LRS that includes debugging tools that log HTTP errors? Let me know if you need a recommendation of an LRS that has these tools.

**Comment by bstevens762** [comment]
Andrew,

Thanks for your response. I am currently contacting our partner company for
the exact program being used to run the LRS, but I seemed to run into the
same issue when attempting to post to my free SCORM LRS. Also, Im confused
as to why 200OK is fine in this case. Using TinCan API with Unity, the
script checks the HTTP status code and if it returns as 200 OK then the
function returns with 'False' for lrsResponse.success, and also does not
bother to assign a UUID to the statement, as it seems it has already
failed. Is this a misunderstanding of mine in regards to how tincan is
sending the statement in the first place? If I force a UUID onto the
statement beforehand, it returns with code 204, No Content. Thank you again
for your time, and help.

Sincerely,
Brett Stevens

**Comment by brianjmiller** [comment]
It would likely help to see a code snippet of what you are using to send the statements. In addition to checking the `lrsResponse.success` value, it would be helpful to know what values are stored in `lrsResponse.httpException` and/or what is in `lrsResponse.errMsg` which should both get set when `lrsResponse.success` is `false`.

**Comment by bstevens762** [comment]
Brian,

Attached are two code snips from the project. First is my script which is
my attempt at sending xAPI statements. Second is the code block in which
statuscode OK fails(this may be unnecessary for you to see). I will check
the values of lrsResponse.httpException and lrsResponse.errMsg. The LRS we
are using is FocalPoint LRS. Thank you once more for your correspondence.

**Comment by brianjmiller** [comment]
@bstevens762 I don't think attachments work through GH, at least not that way. You should inline the code with the "insert code" functionality. Having the values of the two properties is probably more important.

**Comment by bstevens762** [comment]
Brian,

My mistake. Here is my script for contacting the LRS, so far the .errMsg
and the .httpException have been very helpful. WE also noticed that the
company we are working with is not on the confirmed list of conforming LRSs
of xAPI adopters, so we are pushing them to conform to the standards and
adopt.

try
            {

                lrs = new RemoteLRS(
                    "https://cloud.scorm.com/tc/9QWIN1S0NN",
                    "StjFxHTnPdOLFG7KdIM",  //Username = client_id
                    "AEIt-YEGe5JJKIWkaZE"  //password = client_secret
                );

                agent = new Agent();
                agent.mbox = "brettstevens@focusvisionmedia.com";
                agent.name = "Brett Stevens - Edison XAPI Test";

                verb = new Verb();
                verb.id = new Uri("
http://adlnet.gov/expapi/verbs/experienced");
                verb.display = new LanguageMap();
                verb.display.Add("en-US", "experienced");

                act = new Activity();
                act.id = ("http://rusticisoftware.github.io/TinCan.NET");


                state = new Statement();
                state.actor = agent;
                state.verb = verb;
                state.target = act;

                ServicePointManager.ServerCertificateValidationCallback =
MyRemoteCertificateValidationCallback;
                StatementLRSResponse lrsResponse = lrs.SaveStatement(state);
                if (lrsResponse.success)
                {
                    Console.WriteLine("Save Statement: " +
lrsResponse.content.id);
                }
                else if (!lrsResponse.success)
                {
                    Debug.Log(lrsResponse.success);
                    Debug.Log(lrsResponse.errMsg);
                    Debug.Log(lrsResponse.httpException);
                    Debug.Log("Failed to ping LRS");
                }
                sentTest = true;
            }
            catch (WebException ex)
            {
                if (ex != null)
                {
                    using (Stream stream = ex.Response.GetResponseStream())
                    using (StreamReader reader = new StreamReader(stream))
                    {
                        Console.WriteLine(reader.ReadToEnd());
                    }
                }
            }
        }
