### ISSUE TITLE
Activity does not have extensions

### ISSUE THREAD

**Issue by matthewdenobrega** [RusticiSoftware/TinCan.NET#42]
Not sure if I'm missing something, but extensions are in the spec for Activity definitions, but not included in the Activity class.

https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#41-extensions
https://xapi.com/blog/deep-dive-extensions/

http://rusticisoftware.github.io/TinCan.NET/doc/api/latest/html/1ea63af8-e2ba-650d-af37-9288a2e403c3.htm

**Comment by brianjmiller** [comment]
See the `ActivityDefinition` class: http://rusticisoftware.github.io/TinCan.NET/doc/api/latest/html/2cd571a0-d3aa-dc44-4c90-360f0784c663.htm
