### ISSUE TITLE
json to statement conversion

### ISSUE THREAD

**Issue by AnnabellBrocker** [RusticiSoftware/TinCan.NET#48]
Hey everyone,

is it possible to convert a json/string object easily into the statement object?

If the xAPI can not be transmitted to an LRS (due to connection problems or something else) the statement needs to be locally stored. An easy option would be to just save it in an extra json or txt file, but therefore the statement object needs to be converted into json or into a string. In order to transmit the statement later, the string/json needs to be reconverted into a statement.

Thanks in advance
Annabelll

**Comment by reedmclean** [comment]
Annabell,

Have you seen this constructor on the `Statement` class?
https://github.com/RusticiSoftware/TinCan.NET/blob/b865b3939b3a68a21c6251728e301f24e4999322/TinCan/Statement.cs#L34

It accepts a class called `StringOfJSON` as its parameter. You can initialize a `StringOfJSON` with your string using this constructor: 
https://github.com/RusticiSoftware/TinCan.NET/blob/b865b3939b3a68a21c6251728e301f24e4999322/TinCan/json/StringOfJSON.cs#L25

Then, you can use that `StringOfJSON` to initialize a new `Statement`, and it should populate the object with the details from your JSON string.

You can find an example of this behavior in the tests. We're using the `Verb` class here, but it should work pretty much the same for a `Statement` or any other JSON-based class: https://github.com/RusticiSoftware/TinCan.NET/blob/ef01bbcbbb3aa959426c9ac74cd0b7b5fc0e531f/TinCanTests/VerbTest.cs#L54-L58

Let me know if that works for you.

**Comment by AnnabellBrocker** [comment]
Yeah this seems to work. Thank you :)
